plugins { id 'com.android.application' }

android {
    namespace 'com.echo.tetrislan'
    compileSdk 35
    signingConfigs {
        fixed {
            storeFile file('tetris.keystore')
            storePassword 'android'
            keyAlias 'tetris'
            keyPassword 'android'
        }
    }
    defaultConfig {
        applicationId 'com.echo.tetrislan'
        minSdk 23
        targetSdk 35
        versionCode 78
        versionName '1.26.23'
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.fixed
        }
    }
    applicationVariants.all { variant ->
        variant.outputs.all {
            outputFileName = "tetrislan_v${variant.versionName}.apk"
        }
    }
}
