plugins { id 'com.android.application' }

android {
    namespace 'com.echo.tetrislan'
    compileSdk 35
    signingConfigs {
        fixed {
            storeFile file(System.getProperty('user.home') + '/.android/tetris.keystore')
            storePassword 'android'
            keyAlias 'tetris'
            keyPassword 'android'
        }
    }
    defaultConfig {
        applicationId 'com.echo.tetrislan'
        minSdk 23
        targetSdk 35
        versionCode 19
        versionName '1.7.3'
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.fixed
        }
    }
}
